# presonal infomation part
resume_name:                    "WanYuan Wang"
resume_chinese_name:            "王万元"
resume_job_title:               "Assistant Professor"
resume_department:              "School of Computer Science and Engineering"
resume_university:              "Southeast University"
resume_contact_email:           "wywang@seu.edu.cn"
resume_contact_telephone:       "0000-00000000"
resume_contact_address:         "Room 508, Computer Building, Jiulonghu Campus of Southeast University,Nanjing, P.R. China"