# presonal infomation part
resume_name:                    "WanYuan Wang"
resume_chinese_name:            "王万元"
resume_biography:               "王万元，硕导。2016年毕业于东南大学获得博士学位，2017年新加坡南洋理工大学从事博士后研究工作。研究方向主要为群集智能，多智能系统，运筹优化，强化学习以及博弈论,在教育、城市交通以及众包等实际应用。欢迎致力于算法解决实际问题的研究生报考！"
resume_job_title:               "Assistant Professor"
resume_department:              "School of Computer Science and Engineering"
resume_university:              "Southeast University"
resume_contact_email:           "wywang@seu.edu.cn"
resume_contact_address:         "Room 508, Computer Building, Jiulonghu Campus of Southeast University,Nanjing, P.R. China"
